name: Development build

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    name: Development build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios
    
    runs-on: macos-14
    steps:
      - name: Remove work folders
        run: |
          echo "before"
          ls -lah ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          echo "after"
          ls -lah ./
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          set-safe-directory: 'true'
      - name: Set up JDK 8
        id: setup-zulu
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Link JDK 8 to macOS System Path and Install Tools
        run: |
          # Use the dynamic JAVA_HOME path provided automatically by the action
          echo "BOOTJDK=$JAVA_HOME" >> $GITHUB_ENV
          
          # Install ldid utility using Homebrew
          brew install ldid

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        shell: bash
        run: |
          SHA=$(git ls-remote https://github.com/ptitseb/gl4es refs/heads/master | awk '{print $1}')
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build for ${{ matrix.platform_name }}
        run: |
          export PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
          export SLIMMED=1
          
          if [ "${{ matrix.platform_name }}" == "ios" ]; then
            # We reference $BOOTJDK which is now bound to the exact java action location
            make -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} BOOTJDK="$BOOTJDK"
            make -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1 BOOTJDK="$BOOTJDK"
          fi
          
      - name: Upload regular ipa
        uses: actions/upload-artifact@v4
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}.ipa

      - name: Upload regular tipa
        uses: actions/upload-artifact@v4
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload slimmed ipa
        uses: actions/upload-artifact@v4
        with:
          name: org.angelauramc.amethyst.slimmed-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst.slimmed-*-${{ matrix.platform_name }}.ipa

      - name: Upload slimmed tipa
        uses: actions/upload-artifact@v4
        with:
          name: org.angelauramc.amethyst.slimmed-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/artifacts/org.angelauramc.amethyst.slimmed-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@v4
        if: matrix.platform_name == 'ios'
        with:
          name: AngelAuraAmethyst.dSYM
          path: artifacts/AngelAuraAmethyst.dSYM
